

### Step 1. Import the necessary libraries

In [2]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset Euro_2012_stats_TEAM

### Step 3. Assign it to a variable called euro12.

In [3]:
euro12=pd.read_csv("E:/python/PIAIC-Sir-Anees-Quarter-2-master/PIAIC-Sir-Anees-Quarter-2-master/Assignment-2/Euro_2012_stats_TEAM.csv")
display(euro12)

FileNotFoundError: [Errno 2] File b'E:/python/PIAIC-Sir-Anees-Quarter-2-master/PIAIC-Sir-Anees-Quarter-2-master/Assignment-2/Euro_2012_stats_TEAM.csv' does not exist: b'E:/python/PIAIC-Sir-Anees-Quarter-2-master/PIAIC-Sir-Anees-Quarter-2-master/Assignment-2/Euro_2012_stats_TEAM.csv'

### Step 4. Select only the Goal column.

In [4]:
euro12.Goals

0      4.0
1      4.0
2      4.0
3      5.0
4      3.0
5     10.0
6      5.0
7      6.0
8      2.0
9      2.0
10     6.0
11     1.0
12     5.0
13    12.0
14     5.0
15     2.0
16     NaN
17     NaN
18     NaN
19     NaN
Name: Goals, dtype: float64

### Step 5. How many team participated in the Euro2012?

In [5]:
c=0
for i in euro12.Team:
    c+=1
print("Teams are:",c)

Teams are: 20

### Step 6. What is the number of columns in the dataset?

In [6]:
len(euro12.columns)

35

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [35]:
y=euro12['Yellow Cards']
r=euro12['Red Cards']
t=euro12['Team']
d={"Yellow_card":y,"Red_card":r,"Teams":t}
discipline=pd.DataFrame(d)
display(discipline)

    Yellow_card  Red_card                                              Teams
0           9.0       0.0                                            Croatia
1           7.0       0.0                                     Czech Republic
2           4.0       0.0                                            Denmark
3           5.0       0.0                                            England
4           6.0       0.0                                             France
5           4.0       0.0                                            Germany
6           9.0       1.0                                             Greece
7          16.0       0.0                                              Italy
8           5.0       0.0                                        Netherlands
9           7.0       1.0                                             Poland
10         12.0       0.0                                           Portugal
11          6.0       1.0                                Republic of Ireland
12          6.0       0.0                                             Russia
13         11.0       0.0                                              Spain
14          7.0       0.0                                             Sweden
15          5.0       0.0                                            Ukraine
16          NaN       NaN                                                NaN
17          NaN       NaN                                                NaN
18          NaN       NaN                                                NaN
19          NaN       NaN  https://towardsdatascience.com/data-handling-u...

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

In [28]:
s=discipline.sort_values(by="Red_card")
print(s)
aa=discipline.sort_values(by="Yellow_card")
print(aa)

    Yellow_card  Red_card                                              Teams
0           9.0       0.0                                            Croatia
1           7.0       0.0                                     Czech Republic
2           4.0       0.0                                            Denmark
3           5.0       0.0                                            England
4           6.0       0.0                                             France
5           4.0       0.0                                            Germany
7          16.0       0.0                                              Italy
8           5.0       0.0                                        Netherlands
10         12.0       0.0                                           Portugal
12          6.0       0.0                                             Russia
13         11.0       0.0                                              Spain
14          7.0       0.0                                             Sweden
15          5.0       0.0                                            Ukraine
6           9.0       1.0                                             Greece
9           7.0       1.0                                             Poland
11          6.0       1.0                                Republic of Ireland
16          NaN       NaN                                                NaN
17          NaN       NaN                                                NaN
18          NaN       NaN                                                NaN
19          NaN       NaN  https://towardsdatascience.com/data-handling-u...
    Yellow_card  Red_card                                              Teams
2           4.0       0.0                                            Denmark
5           4.0       0.0                                            Germany
3           5.0       0.0                                            England
8           5.0       0.0                                        Netherlands
15          5.0       0.0                                            Ukraine
4           6.0       0.0                                             France
11          6.0       1.0                                Republic of Ireland
12          6.0       0.0                                             Russia
1           7.0       0.0                                     Czech Republic
9           7.0       1.0                                             Poland
14          7.0       0.0                                             Sweden
0           9.0       0.0                                            Croatia
6           9.0       1.0                                             Greece
13         11.0       0.0                                              Spain
10         12.0       0.0                                           Portugal
7          16.0       0.0                                              Italy
16          NaN       NaN                                                NaN
17          NaN       NaN                                                NaN
18          NaN       NaN                                                NaN
19          NaN       NaN  https://towardsdatascience.com/data-handling-u...

### Step 9. Calculate the mean Yellow Cards given per Team

In [41]:
#discipline.fillna({'Yellow_card':0})
df=discipline.fillna(0)
display(df)
sum=0
c=0
for h in df["Yellow_card"]:
    h=float(h)
    sum=sum+h
    c+=1
print("Mean",sum/c)

    Yellow_card  Red_card                                              Teams
0           9.0       0.0                                            Croatia
1           7.0       0.0                                     Czech Republic
2           4.0       0.0                                            Denmark
3           5.0       0.0                                            England
4           6.0       0.0                                             France
5           4.0       0.0                                            Germany
6           9.0       1.0                                             Greece
7          16.0       0.0                                              Italy
8           5.0       0.0                                        Netherlands
9           7.0       1.0                                             Poland
10         12.0       0.0                                           Portugal
11          6.0       1.0                                Republic of Ireland
12          6.0       0.0                                             Russia
13         11.0       0.0                                              Spain
14          7.0       0.0                                             Sweden
15          5.0       0.0                                            Ukraine
16          0.0       0.0                                                  0
17          0.0       0.0                                                  0
18          0.0       0.0                                                  0
19          0.0       0.0  https://towardsdatascience.com/data-handling-u...

Mean 5.95

### Step 10. Filter teams that scored more than 6 goals

In [45]:
euro12[euro12.Goals>6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10.0,32.0,32.0,47.80%,15.60%,80.0,2.0,1.0,0.0,...,10.0,62.60%,63.0,49.0,12.0,4.0,0.0,15.0,15.0,17.0
13,Spain,12.0,42.0,33.0,55.90%,16.00%,100.0,0.0,1.0,0.0,...,15.0,93.80%,102.0,83.0,19.0,11.0,0.0,17.0,17.0,18.0

### Step 11. Select the teams that start with G

In [58]:
df=euro12.fillna({"Team":"mising"})
#print(df)
for i in df.Team:
    if i.startswith("G"):
        print(i)

Germany
Greece

### Step 12. Select the first 7 columns

In [118]:
euro12.iloc[0:,:7]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked)
0,Croatia,4.0,13.0,12.0,51.90%,16.00%,32.0
1,Czech Republic,4.0,13.0,18.0,41.90%,12.90%,39.0
2,Denmark,4.0,10.0,10.0,50.00%,20.00%,27.0
3,England,5.0,11.0,18.0,50.00%,17.20%,40.0
4,France,3.0,22.0,24.0,37.90%,6.50%,65.0
5,Germany,10.0,32.0,32.0,47.80%,15.60%,80.0
6,Greece,5.0,8.0,18.0,30.70%,19.20%,32.0
7,Italy,6.0,34.0,45.0,43.00%,7.50%,110.0
8,Netherlands,2.0,12.0,36.0,25.00%,4.10%,60.0
9,Poland,2.0,15.0,23.0,39.40%,5.20%,48.0
10,Portugal,6.0,22.0,42.0,34.30%,9.30%,82.0
11,Republic of Ireland,1.0,7.0,12.0,36.80%,5.20%,28.0
12,Russia,5.0,9.0,31.0,22.50%,12.50%,59.0
13,Spain,12.0,42.0,33.0,55.90%,16.00%,100.0
14,Sweden,5.0,17.0,19.0,47.20%,13.80%,39.0
15,Ukraine,2.0,7.0,26.0,21.20%,6.00%,38.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,https://towardsdatascience.com/data-handling-u...,NaN,NaN,NaN,NaN,NaN,NaN

### Step 13. Select all columns except the last 3.

In [111]:

euro12.iloc[:,:-3]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards
0,Croatia,4.0,13.0,12.0,51.90%,16.00%,32.0,0.0,0.0,0.0,...,0.0,10.0,3.0,13.0,81.30%,41.0,62.0,2.0,9.0,0.0
1,Czech Republic,4.0,13.0,18.0,41.90%,12.90%,39.0,0.0,0.0,0.0,...,1.0,10.0,6.0,9.0,60.10%,53.0,73.0,8.0,7.0,0.0
2,Denmark,4.0,10.0,10.0,50.00%,20.00%,27.0,1.0,0.0,0.0,...,1.0,10.0,5.0,10.0,66.70%,25.0,38.0,8.0,4.0,0.0
3,England,5.0,11.0,18.0,50.00%,17.20%,40.0,0.0,0.0,0.0,...,2.0,29.0,3.0,22.0,88.10%,43.0,45.0,6.0,5.0,0.0
4,France,3.0,22.0,24.0,37.90%,6.50%,65.0,1.0,0.0,0.0,...,1.0,7.0,5.0,6.0,54.60%,36.0,51.0,5.0,6.0,0.0
5,Germany,10.0,32.0,32.0,47.80%,15.60%,80.0,2.0,1.0,0.0,...,1.0,11.0,6.0,10.0,62.60%,63.0,49.0,12.0,4.0,0.0
6,Greece,5.0,8.0,18.0,30.70%,19.20%,32.0,1.0,1.0,1.0,...,1.0,23.0,7.0,13.0,65.10%,67.0,48.0,12.0,9.0,1.0
7,Italy,6.0,34.0,45.0,43.00%,7.50%,110.0,2.0,0.0,0.0,...,2.0,18.0,7.0,20.0,74.10%,101.0,89.0,16.0,16.0,0.0
8,Netherlands,2.0,12.0,36.0,25.00%,4.10%,60.0,2.0,0.0,0.0,...,0.0,9.0,5.0,12.0,70.60%,35.0,30.0,3.0,5.0,0.0
9,Poland,2.0,15.0,23.0,39.40%,5.20%,48.0,0.0,0.0,0.0,...,0.0,8.0,3.0,6.0,66.70%,48.0,56.0,3.0,7.0,1.0
10,Portugal,6.0,22.0,42.0,34.30%,9.30%,82.0,6.0,0.0,0.0,...,2.0,11.0,4.0,10.0,71.50%,73.0,90.0,10.0,12.0,0.0
11,Republic of Ireland,1.0,7.0,12.0,36.80%,5.20%,28.0,0.0,0.0,0.0,...,0.0,23.0,9.0,17.0,65.40%,43.0,51.0,11.0,6.0,1.0
12,Russia,5.0,9.0,31.0,22.50%,12.50%,59.0,2.0,0.0,0.0,...,0.0,8.0,3.0,10.0,77.00%,34.0,43.0,4.0,6.0,0.0
13,Spain,12.0,42.0,33.0,55.90%,16.00%,100.0,0.0,1.0,0.0,...,5.0,8.0,1.0,15.0,93.80%,102.0,83.0,19.0,11.0,0.0
14,Sweden,5.0,17.0,19.0,47.20%,13.80%,39.0,3.0,0.0,0.0,...,1.0,12.0,5.0,8.0,61.60%,35.0,51.0,7.0,7.0,0.0
15,Ukraine,2.0,7.0,26.0,21.20%,6.00%,38.0,0.0,0.0,0.0,...,0.0,4.0,4.0,13.0,76.50%,48.0,31.0,4.0,5.0,0.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,https://towardsdatascience.com/data-handling-u...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [87]:
euro1=pd.read_csv("E:/python/PIAIC-Sir-Anees-Quarter-2-master/PIAIC-Sir-Anees-Quarter-2-master/Assignment-2/Euro_2012_stats_TEAM.csv",index_col="Team")
#display(euro12)
euro1.index_col='Team'
euro1.loc[['England','Italy','Russia'],["Shooting Accuracy"]]

        Shooting Accuracy
Team
England            50.00%
Italy              43.00%
Russia             22.50%

### Step 15. Use apply method on Goal Column to make a new column called Performance, using following conditions

1. If Goals are less than or equal to 2, peformance is **Below Avg**
2. If Goals are more than 2 and less than or equal to 5, peformance is **Average**
3. If Goals are more than 5 and less than or equal to 10, peformance is **Above Average**
4. If Goals are more than 10 then peformance is **Excellent**

In [123]:
#print(euro12.Goals)
s=pd.Series(euro12.Goals)
for i in s:
    if i<=2:
        print("Below Average=",i)
    elif i>=2 and i<=5:
        print(" Average=",i)
    elif i>=5 and i<=10:
        print(" above average=",i)
    else:
        print('excellent')

 Average= 4.0
 Average= 4.0
 Average= 4.0
 Average= 5.0
 Average= 3.0
 above average= 10.0
 Average= 5.0
 above average= 6.0
Below Average= 2.0
Below Average= 2.0
 above average= 6.0
Below Average= 1.0
 Average= 5.0
excellent
 Average= 5.0
Below Average= 2.0
excellent
excellent
excellent
excellent